# Values here are the same across all environments
generic-service:
  nameOverride: offender-case-notes
  productId: DPS067

  image:
    repository: quay.io/hmpps/offender-case-notes
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    v1_2_enabled: true
    v0_47_enabled: false
    annotations:
      nginx.ingress.kubernetes.io/server-snippet: |
        server_tokens off;
        location /queue-admin/retry-all-dlqs {
          deny all;
          return 401;
        }
    tlsSecretName: offender-case-notes-cert

  serviceAccountName: offender-case-notes

  env:
    SERVER_PORT: 8080
    JAVA_OPTS: "-Xmx512m"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY);IngestionEndpoint=https://northeurope-0.in.applicationinsights.azure.com/;LiveEndpoint=https://northeurope.livediagnostics.monitor.azure.com/"
    SNS_PROVIDER: "aws"
    HMPPS_SQS_USE_WEB_TOKEN: true
    SENTRY_TRACES_SAMPLE_RATE: '0.05'
    SENTRY_IGNORED_EXCEPTIONS_FOR_TYPE: "org.apache.catalina.connector.ClientAbortException"

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    offender-case-notes:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      OFFENDER_CASE_NOTES_CLIENT_ID: "OFFENDER_CASE_NOTES_CLIENT_ID"
      OFFENDER_CASE_NOTES_CLIENT_SECRET: "OFFENDER_CASE_NOTES_CLIENT_SECRET"
      SENTRY_DSN: SENTRY_DSN
      SENTRY_AUTH_TOKEN: SENTRY_AUTH_TOKEN
    dps-rds-instance-output:
      DATABASE_USERNAME: "database_username"
      DATABASE_PASSWORD: "database_password"
      DATABASE_NAME: "database_name"
      DATABASE_ENDPOINT: "rds_instance_endpoint"
    hmpps-domain-events-topic:
      HMPPS_SQS_TOPICS_DOMAINEVENTS_ARN: "topic_arn"
    ocn-events-sqs-instance-output:
      HMPPS_SQS_QUEUES_EVENT_QUEUE_NAME: "sqs_ocne_name"
    ocn-events-sqs-dl-instance-output:
      HMPPS_SQS_QUEUES_EVENT_DLQ_NAME: "sqs_ocne_name"

  allowlist:
    groups:
      - internal

generic-prometheus-alerts:
  targetApplication: offender-case-notes
