---
# Values here are the same across all environments
generic-service:
  nameOverride: offender-case-notes

  image:
    repository: quay.io/hmpps/offender-case-notes
    tag: app_version    # override at deployment time
    port: 8080

  ingress:
    enabled: true
    v1_2_enabled: true
    v0_47_enabled: false
    annotations:
      nginx.ingress.kubernetes.io/configuration-snippet: |
        server_tokens off;
        location /queue-admin/retry-all-dlqs {
          deny all;
          return 401;
        }
    tlsSecretName: offender-case-notes-cert

  serviceAccountName: offender-case-notes

  env:
    SERVER_PORT: 8080
    JAVA_OPTS: "-Xmx512m"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY);IngestionEndpoint=https://northeurope-0.in.applicationinsights.azure.com/;LiveEndpoint=https://northeurope.livediagnostics.monitor.azure.com/"
    SNS_PROVIDER: "aws"
    HMPPS_SQS_USE_WEB_TOKEN: true

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    offender-case-notes:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      OFFENDER_CASE_NOTES_CLIENT_ID: "OFFENDER_CASE_NOTES_CLIENT_ID"
      OFFENDER_CASE_NOTES_CLIENT_SECRET: "OFFENDER_CASE_NOTES_CLIENT_SECRET"
    dps-rds-instance-output:
      DATABASE_USERNAME: "database_username"
      DATABASE_PASSWORD: "database_password"
      DATABASE_NAME: "database_name"
      DATABASE_ENDPOINT: "rds_instance_endpoint"
    hmpps-domain-events-topic:
      HMPPS_SQS_TOPICS_DOMAINEVENTS_ARN: "topic_arn"
    ocn-events-sqs-instance-output:
      HMPPS_SQS_QUEUES_EVENT_QUEUE_NAME: "sqs_ocne_name"
    ocn-events-sqs-dl-instance-output:
      HMPPS_SQS_QUEUES_EVENT_DLQ_NAME: "sqs_ocne_name"

  allowlist:
    office: "217.33.148.210/32"
    health-kick: "35.177.252.195/32"
    mojvpn: "81.134.202.29/32"
    petty-france-wifi: "213.121.161.112/28"
    global-protect: "35.176.93.186/32"
    cloudplatform-live1-1: "35.178.209.113/32"
    cloudplatform-live1-2: "3.8.51.207/32"
    cloudplatform-live1-3: "35.177.252.54/32"

generic-prometheus-alerts:
  targetApplication: offender-case-notes
