version: "3"
services:
  localstack:
    image: localstack/localstack:3.0
    networks:
      - hmpps
    container_name: localstack
    ports:
      - "4566-4597:4566-4597"
    environment:
      - SERVICES=sqs,sns
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  hmpps:
