services:
  db:
    image: postgres:17
    networks:
      - hmpps
    container_name: offender-case-notes-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=case_notes
      - POSTGRES_USER=case
      - POSTGRES_PASSWORD=notes

  localstack:
    image: localstack/localstack:4
    networks:
      - hmpps
    container_name: localstack
    ports:
      - "4567-4598:4566-4597"
    environment:
      - SERVICES=sqs,sns
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  hmpps:
