version: "3"
services:
  offender-case-notes:
    image: quay.io/hmpps/offender-case-notes:latest
    networks:
      - hmpps
    container_name: offender-case-notes
    depends_on:
      - offender-case-notes-db
      - localstack
    ports:
      - "8083:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://offender-case-notes-db/offender-case-notes
      - SPRING_DATASOURCE_USERNAME=offender-case-notes
      - SPRING_DATASOURCE_PASSWORD=offender-case-notes
      - ELITE2_API_BASE_URL=http://elite2-api:8080
      - OAUTH_API_BASE_URL=http://oauth:8080/auth
      - SPRING_PROFILES_ACTIVE=stdout,localstack
      - JWT_PUBLIC_KEY=LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0NCk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBc09QQXRzUUFEZGJSdS9FSDZMUDUNCkJNMS9tRjQwVkRCbjEyaEpTWFBQZDVXWUswSExZMjBWTTdBeHhSOW1uWUNGNlNvMVd0N2ZHTnFVeC9XeWVtQnANCklKTnJzLzdEendnM3V3aVF1Tmg0ektSK0VHeFdiTHdpM3l3N2xYUFV6eFV5QzV4dDg4ZS83dk8rbHoxb0NuaXoNCmpoNG14TkFtczZaWUY3cWZuaEpFOVd2V1B3TExrb2prWnUxSmR1c0xhVm93TjdHVEdOcE1FOGR6ZUprYW0wZ3ANCjRveEhRR2hNTjg3SzZqcVgzY0V3TzZEdmhlbWc4d2hzOTZuelFsOG4yTEZ2QUsydXA5UHJyOUdpMkxGZ1R0N0sNCnFYQTA2a0M0S2d3MklSMWVGZ3pjQmxUT0V3bXpqcmU2NUhvTmFKQnI5dU5aelY1c0lMUE1jenpoUWovZk1oejMNCi9RSURBUUFCDQotLS0tLUVORCBQVUJMSUMgS0VZLS0tLS0=
      - SQS_ENDPOINT_URL=http://localstack:4576

  elite2-api:
    image: quay.io/hmpps/elite2-api:latest
    networks:
      - hmpps
    container_name: elite2-api
    depends_on:
      - oauth
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=nomis-hsqldb

  oauth:
    image: quay.io/hmpps/nomis-oauth2-server:latest
    networks:
      - hmpps
    container_name: oauth
    ports:
      - "9090:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/health"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev

  offender-case-notes-db:
    image: postgres
    networks:
      - hmpps
    container_name: offender-case-notes-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=offender-case-notes
      - POSTGRES_USER=offender-case-notes
      - POSTGRES_DB=offender-case-notes

  localstack:
    image: localstack/localstack:0.10.4
    networks:
      - hmpps
    container_name: localstack
    ports:
      - "4567-4597:4567-4597"
      - 9001:8080
    environment:
      HOSTNAME_EXTERNAL: localstack
      SERVICES: sns,sqs
      AWS_EXECUTION_ENV: "true"
      DEFAULT_REGION: eu-west-2

networks:
  hmpps:
