spring:
  application:
    name: offender-case-notes

  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
            
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: classpath:db/migration/general,classpath:db/migration/{vendor}

  datasource:
    url: 'jdbc:postgresql://${DATABASE_ENDPOINT}/${DATABASE_NAME}?sslmode=verify-full'
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    continue-on-error: true

    hikari:
      pool-name: OffenderCaseNotes-CP
      connectionTimeout: 1000
      validationTimeout:  500

  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  security:
    oauth2:
      client:
        registration:
          elite2-api:
            provider: hmpps-auth
            client-id: ${oauth.client.id}
            client-secret: ${oauth.client.secret}
            authorization-grant-type: client_credentials
            scope: read
        provider:
          hmpps-auth:
            token-uri: ${oauth.endpoint.url}/oauth/token
  codec:
    max-in-memory-size: 10MB


server:
  port: 8080
  servlet:
    context-path: /
  forward-headers-strategy: native
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol_header: x-forwarded-proto

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: 'info, health, ping'
  endpoint:
    health:
      cache:
        time-to-live: 2000ms
      show-components: always
      show-details: always
    info:
      cache:
        time-to-live: 2000ms

graceful:
  shutdown:
    enabled: true

azure:
  application-insights:
    web:
      enable-W3C: true


offendercasenotes:
  client:
    client-id: ${offender.case.notes.client.id}
    client-secret: ${offender.case.notes.client.secret}
    access-token-uri: ${oauth.api.base.url}/oauth/token
    authentication-scheme: header
    client-authentication-scheme: header

sns:
  endpoint.region: eu-west-2

sqs:
  provider: aws
  endpoint.region: eu-west-2
