sns:
  provider: localstack
  endpoint.url: http://localhost:4575
  topic.arn: arn:aws:sns:eu-west-2:000000000000:offender_events

sqs:
  provider: localstack
  queue.name: offender_case_notes_queue
  dlq.name: offender_case_notes_dlq
  endpoint.url: http://localhost:4576
