spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:local-public-key.pub

  flyway:
    enabled: true
    locations: classpath:db/migration/general,classpath:db/migration/{vendor},classpath:db/test/migration

  jpa:
    show-sql: true

server:
  shutdown: immediate

service.base-url: http://localhost:8080

elite2:
  api.base.url: http://localhost:8080
oauth:
  api.base.url: http://localhost:9090/auth
tokenverification:
  api.base.url: http://localhost:8100
