spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:local-public-key.pub
  datasource:
    url: 'jdbc:h2:mem:offender-case-notes-db;MODE=PostgreSQL'
    username: sa
    password:

  flyway:
    enabled: true
    locations: classpath:db/migration/general,classpath:db/migration/{vendor},classpath:db/test/migration

  h2:
    console:
      enabled: true
  jpa:
    show-sql: true

server:
  shutdown: immediate

casenotes:
  api.base.url: http://localhost:8080
elite2:
  api.base.url: http://localhost:8080
oauth:
  api.base.url: http://localhost:9090/auth
tokenverification:
  api.base.url: http://localhost:8100
