spring:
  application:
    name: offender-case-notes

  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
          batch_size: 500
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: classpath:db/migration/general,classpath:db/migration/{vendor}

  datasource:
    url: 'jdbc:postgresql://${DATABASE_ENDPOINT}/${DATABASE_NAME}?sslmode=verify-full&reWriteBatchedInserts=true'
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      pool-name: OffenderCaseNotes-CP
      connectionTimeout: 10000
      validationTimeout: 500
      maximum-pool-size: 20

  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  security:
    oauth2:
      client:
        registration:
          default:
            provider: hmpps-auth
            client-id: ${offender.case.notes.client.id}
            client-secret: ${offender.case.notes.client.secret}
            authorization-grant-type: client_credentials
            scope: read
        provider:
          hmpps-auth:
            token-uri: ${oauth.api.base.url}/oauth/token
  codec:
    max-in-memory-size: 10MB

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

sentry:
  exception-resolver-order: -2147483647

server:
  port: 8080
  servlet:
    context-path: /
  forward-headers-strategy: native
  tomcat:
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto
  shutdown: graceful

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: 'info, health, ping'
  endpoint:
    health:
      cache:
        time-to-live: 2000ms
      show-components: always
      show-details: always
      probes:
        enabled: true
    info:
      cache:
        time-to-live: 2000ms

service:
  active-prisons:
  base-url:
