hmpps.sqs:
  provider: localstack
  queues:
    event:
      queueName: offender_case_notes_queue
      dlqName: offender_case_notes_dlq
      subscribeTopicId: offenderevents
      subscribeFilter: '{"eventType":[ "BOOKING_NUMBER-CHANGED", "DATA_COMPLIANCE_DELETE-OFFENDER"] }'
  topics:
    offenderevents:
      arn: arn:aws:sns:eu-west-2:000000000000:offender_events
    domainevents:
      arn: arn:aws:sns:eu-west-2:000000000000:domain_events