hmpps.sqs:
  provider: localstack
  queues:
    domaineventsqueue:
      queueName: ${random.uuid}
      dlqName: ${random.uuid}
      subscribeTopicId: domainevents
      subscribeFilter: '{"eventType":["prison-offender-events.prisoner.merged"]}'
  topics:
    offenderevents:
      arn: arn:aws:sns:eu-west-2:000000000000:offender_events
    domainevents:
      arn: arn:aws:sns:eu-west-2:000000000000:domain_events