version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@8


jobs:
  validate:
    executor:
      name: hmpps/java_localstack_postgres_with_db_name
      jdk_tag: "21.0"
      localstack_tag: "3"
      services: "sqs,sns"
      postgres_tag: "16"
      postgres_db: "case_notes"
      postgres_username: "case"
      postgres_password: "notes"
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
            - gradle-
      - run: ./gradlew check
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests
      - persist_to_workspace:
          root: .
          paths:
            - build/libs
            - build.gradle.kts
  performance-tests:
    circleci_ip_ranges: true
    environment:
      JAVA_TOOL_OPTIONS: '-Xmx4g'
    docker:
      - image: cimg/openjdk:21.0
    resource_class: medium+
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
            - gradle-
      - run: ./gradlew gatlingRun
      - store_artifacts:
          path: build/reports/gatling

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - validate:
          filters:
            tags:
              ignore: /.*/
      - hmpps/helm_lint:
          name: helm_lint
      - hmpps/build_multiplatform_docker:
          name: build_docker
          filters:
            branches:
              only:
                - main
      - hmpps/deploy_env:
          name: deploy_dev
          env: "dev"
          jira_update: true
          pipeline_id: <<pipeline.id>>
          pipeline_number: <<pipeline.number>>
          context: hmpps-common-vars
          filters:
            branches:
              only:
                - main
          requires:
            - validate
            - helm_lint
            - build_docker
      - request-preprod-approval:
          type: approval
          requires:
            - deploy_dev
      - request-dev-performance-test-approval:
          type: approval
          requires:
            - deploy_dev
      - performance-tests:
          name: performance_tests_dev
          requires:
            - request-dev-performance-test-approval
      - hmpps/deploy_env:
          name: deploy_preprod
          env: "preprod"
          jira_update: true
          jira_env_type: staging
          pipeline_id: <<pipeline.id>>
          pipeline_number: <<pipeline.number>>
          context:
            - hmpps-common-vars
            - offender-case-notes-preprod
          requires:
            - request-preprod-approval
      - request-prod-approval:
          type: approval
          requires:
            - deploy_preprod
      - request-preprod-performance-test-approval:
          type: approval
          requires:
            - deploy_preprod
      - performance-tests:
          name: performance_tests_preprod
          context:
            - offender-case-notes-preprod
          requires:
            - request-preprod-performance-test-approval
      - hmpps/deploy_env:
          name: deploy_prod
          env: "prod"
          jira_update: true
          jira_env_type: production
          pipeline_id: <<pipeline.id>>
          pipeline_number: <<pipeline.number>>
          slack_notification: true
          slack_channel_name: move-and-improve-alerts
          context:
            - hmpps-common-vars
            - offender-case-notes-prod
          requires:
            - request-prod-approval

  security:
    triggers:
      - schedule:
          cron: "37 6 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/gradle_owasp_dependency_check:
          jdk_tag: "21.0"
          slack_channel: move-and-improve-alerts-non-prod
          context:
            - hmpps-common-vars
      - hmpps/trivy_latest_scan:
          slack_channel: move-and-improve-alerts-non-prod
          context:
            - hmpps-common-vars
      - hmpps/veracode_pipeline_scan:
          slack_channel: move-and-improve-alerts-non-prod
          context:
            - hmpps-common-vars
            - veracode-credentials
  security-weekly:
    triggers:
      - schedule:
          cron: "19 5 * * 1"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/veracode_policy_scan:
          slack_channel: move-and-improve-alerts-non-prod
          context:
            - veracode-credentials
            - hmpps-common-vars

