EXECUTE IMMEDIATE 'ALTER TABLE OFFENDER_CASE_NOTE_AMENDMENT DROP CONSTRAINT ' ||
    QUOTE_IDENT((SELECT CONSTRAINT_NAME
        FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
        WHERE TABLE_SCHEMA = 'PUBLIC' AND TABLE_NAME = 'OFFENDER_CASE_NOTE_AMENDMENT'
            AND CONSTRAINT_TYPE = 'UNIQUE'));

ALTER TABLE OFFENDER_CASE_NOTE_AMENDMENT DROP COLUMN AMEND_SEQUENCE;
--ALTER TABLE OFFENDER_CASE_NOTE_AMENDMENT ADD CONSTRAINT
--    offender_case_note_amendment_offender_case_note_id_key UNIQUE (OFFENDER_CASE_NOTE_ID);
