INSERT INTO CASE_NOTE_PARENT_TYPE (NOTE_TYPE, DESCRIPTION, ACTIVE, CREATE_DATE_TIME, CREATE_USER_ID)
VALUES ('POM', 'POM Notes', true, now(), 'SYSTEM');

INSERT INTO CASE_NOTE_TYPE (PARENT_TYPE, SUB_TYPE, DESCRIPTION, ACTIVE, CREATE_DATE_TIME, CREATE_USER_ID)
VALUES ('POM', 'GEN', 'General POM Note', true, now(), 'SYSTEM');

INSERT INTO CASE_NOTE_TYPE (PARENT_TYPE, SUB_TYPE, DESCRIPTION, ACTIVE, CREATE_DATE_TIME, CREATE_USER_ID)
VALUES ('POM', 'SPECIAL', 'Special POM Note', true, now(), 'SYSTEM');
