apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.name" . }}
type: Opaque
data:
  APPINSIGHTS_INSTRUMENTATIONKEY: {{ .Values.secrets.APPINSIGHTS_INSTRUMENTATIONKEY | b64enc | quote }}
  sns_access_key_id: {{ .Values.secrets.sns_access_key_id | b64enc | quote }}
  sns_secret_access_key: {{ .Values.secrets.sns_secret_access_key | b64enc | quote }}
  sns_topic_arn: {{ .Values.secrets.sns_topic_arn | b64enc | quote }}
