generic-service:
  ingress:
    host: preprod.offender-case-notes.service.justice.gov.uk

  env:
    SENTRY_ENVIRONMENT: preprod
    SERVICE_BASE_URL: "https://preprod.offender-case-notes.service.justice.gov.uk"
    ELITE2_API_BASE_URL: "https://prison-api-preprod.prison.service.justice.gov.uk"
    OAUTH_API_BASE_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    PRISONER_SEARCH_API_BASE_URL: "https://prisoner-search-preprod.prison.service.justice.gov.uk"
    MANAGE_USERS_API_BASE_URL: "https://manage-users-api-preprod.hmpps.service.justice.gov.uk"
    TOKENVERIFICATION_API_BASE_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    TOKENVERIFICATION_ENABLED: "false"
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth/.well-known/jwks.json"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    SERVICE_ACTIVE_PRISONS: "BFI,BRI,BZI,CDI,CKI,CLI,EHI,ESI,EYI,FDI,FWI,HBI,HPI,LTI,LWI,MSI,MTI,NWI,PBI,PFI,RCI,RHI,SLI,WII,WLI,WRI"

  allowlist:
    delius-pre-prod-1: 52.56.240.62/32
    delius-pre-prod-2: 18.130.110.168/32
    delius-pre-prod-3: 35.178.44.184/32

generic-prometheus-alerts:
  alertSeverity: hmpps-alerts-api-non-prod
  rdsAlertsDatabases:
    cloud-platform-5c6377808488916a: 'offender case notes'
    rdsAlertsConnectionThreshold: 360
  businessHoursOnly: true