DROP TABLE IF EXISTS OFFENDER_CASE_NOTE;

CREATE TABLE OFFENDER_CASE_NOTE
(
    OFFENDER_CASE_NOTE_ID SERIAL PRIMARY KEY,
    OFFENDER_IDENTIFIER   VARCHAR(12) NOT NULL,
    LOCATION_ID           VARCHAR(12) NOT NULL,
    STAFF_USERNAME        VARCHAR(32) NOT NULL,
    CASE_NOTE_TYPE        VARCHAR(12) NOT NULL,
    CASE_NOTE_SUB_TYPE    VARCHAR(12) NOT NULL,
    OCCURRENCE_DATE_TIME  TIMESTAMP   NOT NULL,
    NOTE_TEXT             TEXT,
    CREATE_DATE_TIME      TIMESTAMP   NOT NULL,
    CREATE_USER_ID        VARCHAR(32) NOT NULL,
    MODIFY_DATE_TIME      TIMESTAMP,
    MODIFY_USER_ID        VARCHAR(32)
);

COMMENT ON TABLE OFFENDER_CASE_NOTE IS 'Records a case note for an offender';

CREATE INDEX OFFENDER_CASE_NOTE_IDX1 ON OFFENDER_CASE_NOTE(OFFENDER_IDENTIFIER);

CREATE INDEX OFFENDER_CASE_NOTE_IDX2 ON OFFENDER_CASE_NOTE(LOCATION_ID);

CREATE INDEX OFFENDER_CASE_NOTE_IDX3 ON OFFENDER_CASE_NOTE(STAFF_USERNAME);

CREATE INDEX OFFENDER_CASE_NOTE_IDX4 ON OFFENDER_CASE_NOTE(CASE_NOTE_TYPE, CASE_NOTE_SUB_TYPE);

CREATE INDEX OFFENDER_CASE_NOTE_IDX5 ON OFFENDER_CASE_NOTE(OCCURRENCE_DATE_TIME, LOCATION_ID);
