DROP TABLE IF EXISTS CASE_NOTE_PARENT_TYPE;

CREATE TABLE CASE_NOTE_PARENT_TYPE
(
    NOTE_TYPE         VARCHAR(12) NOT NULL PRIMARY KEY,
    DESCRIPTION       VARCHAR(80) NOT NULL,
    ACTIVE            BOOLEAN     NOT NULL DEFAULT true,
    CREATE_DATE_TIME  TIMESTAMP   NOT NULL,
    CREATE_USER_ID    VARCHAR(32) NOT NULL,
    MODIFY_DATE_TIME  TIMESTAMP,
    MODIFY_USER_ID    VARCHAR(32)
);

COMMENT ON TABLE CASE_NOTE_PARENT_TYPE IS 'Holds case note types allowed in this service';

