DROP TABLE IF EXISTS OFFENDER_CASE_NOTE_AMENDMENT;

CREATE TABLE OFFENDER_CASE_NOTE_AMENDMENT
(
    OFFENDER_CASE_NOTE_ID BIGINT      NOT NULL,
    AMEND_SEQUENCE        NUMERIC(5)  NOT NULL,
    LOCATION_ID           VARCHAR(12) NOT NULL,
    STAFF_ID              NUMERIC     NOT NULL,
    NOTE_TEXT             TEXT        NOT NULL,
    CREATE_DATETIME       TIMESTAMP   NOT NULL,
    CREATE_USER_ID        VARCHAR(32) NOT NULL,
    MODIFY_DATETIME       TIMESTAMP,
    MODIFY_USER_ID        VARCHAR(32),
    PRIMARY KEY (OFFENDER_CASE_NOTE_ID, AMEND_SEQUENCE),
    FOREIGN KEY (OFFENDER_CASE_NOTE_ID) REFERENCES OFFENDER_CASE_NOTE (OFFENDER_CASE_NOTE_ID)
);

COMMENT ON TABLE OFFENDER_CASE_NOTE_AMENDMENT IS 'Records a case note amendments for an offender';




