name: SchemaSpy on push

on:
  push:
    branches:
      - main

jobs:
  schema-spy:
    uses: ./.github/workflows/schema-spy.yml
    with:
      docker_compose_file: 'docker-compose-schema-spy.yml'
      init_db_cli: './gradlew initialiseDatabase'
      database_name: 'offender-case-notes'
      database_user: 'offender-case-notes'
      database_password: 'offender-case-notes'
      database_schema: 'public'
    secrets: inherit